CHECKLIST_MAP: dict[str, str] = {
    "web": "wstg",
    "ios": "mstg_ios",
    "android": "mstg_android",
    "iot": "istg",
    "ai": "aitg",
}

_WSTG_ITEMS: list[dict] = [
    # ── INFO: Information Gathering ──
    {"check_id": "WSTG-INFO-01", "category": "Information Gathering",
     "name": "Разведка через поисковые системы",
     "short_description": "Поиск утечек информации о приложении через поисковые системы и кеши.",
     "goal": "Выявить публично доступную информацию, раскрытую через индексацию поисковыми системами."},
    {"check_id": "WSTG-INFO-02", "category": "Information Gathering",
     "name": "Определение веб-сервера",
     "short_description": "Идентификация типа и версии веб-сервера.",
     "goal": "Определить тип и версию веб-сервера для поиска известных уязвимостей."},
    {"check_id": "WSTG-INFO-03", "category": "Information Gathering",
     "name": "Анализ метафайлов веб-сервера",
     "short_description": "Проверка robots.txt, sitemap.xml и других метафайлов на утечку информации.",
     "goal": "Выявить скрытые директории и конфиденциальную информацию через метафайлы."},
    {"check_id": "WSTG-INFO-04", "category": "Information Gathering",
     "name": "Перечисление приложений на веб-сервере",
     "short_description": "Обнаружение всех приложений, размещённых на веб-сервере.",
     "goal": "Составить полный список приложений на сервере для определения поверхности атаки."},
    {"check_id": "WSTG-INFO-05", "category": "Information Gathering",
     "name": "Анализ содержимого веб-страниц",
     "short_description": "Проверка исходного кода страниц на утечку конфиденциальных данных.",
     "goal": "Обнаружить комментарии, метаданные и скрытую информацию в коде страниц."},
    {"check_id": "WSTG-INFO-06", "category": "Information Gathering",
     "name": "Определение точек входа в приложение",
     "short_description": "Идентификация всех точек ввода данных и параметров приложения.",
     "goal": "Составить карту всех точек входа для последующего тестирования."},
    {"check_id": "WSTG-INFO-07", "category": "Information Gathering",
     "name": "Построение карты путей выполнения",
     "short_description": "Анализ логических путей выполнения и потоков данных в приложении.",
     "goal": "Понять логику работы приложения и определить критичные пути выполнения."},
    {"check_id": "WSTG-INFO-08", "category": "Information Gathering",
     "name": "Определение фреймворка веб-приложения",
     "short_description": "Идентификация используемого фреймворка и его версии.",
     "goal": "Определить фреймворк для поиска специфичных уязвимостей и мисконфигураций."},
    {"check_id": "WSTG-INFO-09", "category": "Information Gathering",
     "name": "Определение веб-приложения",
     "short_description": "Идентификация типа и технологий веб-приложения.",
     "goal": "Определить используемые технологии для выявления характерных уязвимостей."},
    {"check_id": "WSTG-INFO-10", "category": "Information Gathering",
     "name": "Построение архитектуры приложения",
     "short_description": "Составление карты компонентов архитектуры приложения.",
     "goal": "Понять архитектуру приложения для определения всех потенциальных целей атаки."},

    # ── CONF: Configuration and Deployment Management ──
    {"check_id": "WSTG-CONF-01", "category": "Configuration and Deployment Management",
     "name": "Проверка конфигурации сетевой инфраструктуры",
     "short_description": "Тестирование конфигурации сетевых компонентов инфраструктуры.",
     "goal": "Выявить слабые места в конфигурации сетевой инфраструктуры."},
    {"check_id": "WSTG-CONF-02", "category": "Configuration and Deployment Management",
     "name": "Проверка конфигурации платформы приложения",
     "short_description": "Тестирование настроек платформы, на которой развёрнуто приложение.",
     "goal": "Обнаружить небезопасные настройки платформы по умолчанию."},
    {"check_id": "WSTG-CONF-03", "category": "Configuration and Deployment Management",
     "name": "Проверка обработки расширений файлов",
     "short_description": "Анализ обработки различных расширений файлов веб-сервером.",
     "goal": "Выявить возможность загрузки и выполнения файлов с опасными расширениями."},
    {"check_id": "WSTG-CONF-04", "category": "Configuration and Deployment Management",
     "name": "Поиск резервных и устаревших файлов",
     "short_description": "Обнаружение старых бэкапов и неиспользуемых файлов на сервере.",
     "goal": "Найти забытые файлы, содержащие конфиденциальную информацию."},
    {"check_id": "WSTG-CONF-05", "category": "Configuration and Deployment Management",
     "name": "Обнаружение административных интерфейсов",
     "short_description": "Поиск панелей администрирования приложения и инфраструктуры.",
     "goal": "Выявить доступные административные интерфейсы для оценки их защищённости."},
    {"check_id": "WSTG-CONF-06", "category": "Configuration and Deployment Management",
     "name": "Проверка HTTP-методов",
     "short_description": "Тестирование поддерживаемых HTTP-методов на небезопасные конфигурации.",
     "goal": "Обнаружить разрешённые опасные HTTP-методы (PUT, DELETE, TRACE и др.)."},
    {"check_id": "WSTG-CONF-07", "category": "Configuration and Deployment Management",
     "name": "Проверка HTTP Strict Transport Security",
     "short_description": "Анализ настройки заголовка HSTS и принудительного использования HTTPS.",
     "goal": "Убедиться в корректной настройке HSTS для защиты от понижения протокола."},
    {"check_id": "WSTG-CONF-08", "category": "Configuration and Deployment Management",
     "name": "Проверка кросс-доменной политики RIA",
     "short_description": "Анализ файлов crossdomain.xml и clientaccesspolicy.xml.",
     "goal": "Выявить чрезмерно разрешительные кросс-доменные политики."},
    {"check_id": "WSTG-CONF-09", "category": "Configuration and Deployment Management",
     "name": "Проверка прав доступа к файлам",
     "short_description": "Тестирование прав доступа к файлам и директориям на сервере.",
     "goal": "Обнаружить файлы с избыточными правами доступа."},
    {"check_id": "WSTG-CONF-10", "category": "Configuration and Deployment Management",
     "name": "Проверка перехвата поддоменов",
     "short_description": "Тестирование возможности захвата неиспользуемых поддоменов.",
     "goal": "Выявить поддомены, подверженные перехвату через неактивные DNS-записи."},
    {"check_id": "WSTG-CONF-11", "category": "Configuration and Deployment Management",
     "name": "Проверка облачного хранилища",
     "short_description": "Тестирование конфигурации облачных хранилищ на публичный доступ.",
     "goal": "Обнаружить неправильно сконфигурированные облачные хранилища с открытым доступом."},

    # ── IDNT: Identity Management ──
    {"check_id": "WSTG-IDNT-01", "category": "Identity Management",
     "name": "Проверка определений ролей",
     "short_description": "Анализ модели ролей и привилегий пользователей в системе.",
     "goal": "Оценить корректность определения и разделения ролей пользователей."},
    {"check_id": "WSTG-IDNT-02", "category": "Identity Management",
     "name": "Проверка процесса регистрации",
     "short_description": "Тестирование механизма регистрации новых пользователей.",
     "goal": "Выявить уязвимости в процессе создания учётных записей."},
    {"check_id": "WSTG-IDNT-03", "category": "Identity Management",
     "name": "Проверка процесса управления учётными записями",
     "short_description": "Тестирование процессов создания, изменения и удаления аккаунтов.",
     "goal": "Оценить безопасность жизненного цикла управления учётными записями."},
    {"check_id": "WSTG-IDNT-04", "category": "Identity Management",
     "name": "Перечисление и подбор учётных записей",
     "short_description": "Проверка возможности перечисления существующих пользователей.",
     "goal": "Определить, можно ли узнать существующие имена пользователей через ответы системы."},
    {"check_id": "WSTG-IDNT-05", "category": "Identity Management",
     "name": "Проверка политики имён пользователей",
     "short_description": "Анализ требований к именам пользователей и их предсказуемости.",
     "goal": "Выявить слабую или отсутствующую политику именования учётных записей."},

    # ── ATHN: Authentication ──
    {"check_id": "WSTG-ATHN-01", "category": "Authentication",
     "name": "Передача учётных данных по зашифрованному каналу",
     "short_description": "Проверка шифрования при передаче логинов и паролей.",
     "goal": "Убедиться, что учётные данные передаются только по защищённому каналу."},
    {"check_id": "WSTG-ATHN-02", "category": "Authentication",
     "name": "Проверка учётных данных по умолчанию",
     "short_description": "Тестирование на наличие стандартных логинов и паролей.",
     "goal": "Обнаружить неизменённые учётные данные по умолчанию."},
    {"check_id": "WSTG-ATHN-03", "category": "Authentication",
     "name": "Проверка механизма блокировки учётных записей",
     "short_description": "Тестирование защиты от перебора паролей через блокировку.",
     "goal": "Оценить эффективность механизма блокировки при множественных неудачных попытках входа."},
    {"check_id": "WSTG-ATHN-04", "category": "Authentication",
     "name": "Обход схемы аутентификации",
     "short_description": "Тестирование возможности обхода механизма аутентификации.",
     "goal": "Проверить устойчивость схемы аутентификации к различным методам обхода."},
    {"check_id": "WSTG-ATHN-05", "category": "Authentication",
     "name": "Проверка функции «Запомнить пароль»",
     "short_description": "Анализ безопасности хранения запомненных учётных данных.",
     "goal": "Выявить небезопасное хранение учётных данных в функции запоминания пароля."},
    {"check_id": "WSTG-ATHN-06", "category": "Authentication",
     "name": "Проверка кеша браузера",
     "short_description": "Тестирование кеширования страниц с конфиденциальными данными.",
     "goal": "Обнаружить кеширование страниц аутентификации и конфиденциальных данных."},
    {"check_id": "WSTG-ATHN-07", "category": "Authentication",
     "name": "Проверка парольной политики",
     "short_description": "Анализ требований к сложности и длине паролей.",
     "goal": "Оценить надёжность парольной политики приложения."},
    {"check_id": "WSTG-ATHN-08", "category": "Authentication",
     "name": "Проверка контрольных вопросов",
     "short_description": "Тестирование безопасности секретных вопросов для восстановления доступа.",
     "goal": "Выявить слабые контрольные вопросы, ответы на которые легко угадать."},
    {"check_id": "WSTG-ATHN-09", "category": "Authentication",
     "name": "Проверка функций смены и сброса пароля",
     "short_description": "Тестирование механизмов изменения и восстановления пароля.",
     "goal": "Обнаружить уязвимости в процессе смены и сброса пароля."},
    {"check_id": "WSTG-ATHN-10", "category": "Authentication",
     "name": "Проверка аутентификации в альтернативных каналах",
     "short_description": "Тестирование аутентификации через мобильные и другие интерфейсы.",
     "goal": "Выявить ослабленную аутентификацию в альтернативных каналах доступа."},

    # ── ATHZ: Authorization ──
    {"check_id": "WSTG-ATHZ-01", "category": "Authorization",
     "name": "Обход каталогов и включение файлов",
     "short_description": "Тестирование на уязвимости path traversal и file inclusion.",
     "goal": "Проверить возможность доступа к файлам за пределами разрешённых директорий."},
    {"check_id": "WSTG-ATHZ-02", "category": "Authorization",
     "name": "Обход схемы авторизации",
     "short_description": "Тестирование возможности обхода механизма авторизации.",
     "goal": "Проверить устойчивость схемы авторизации к обходу контроля доступа."},
    {"check_id": "WSTG-ATHZ-03", "category": "Authorization",
     "name": "Повышение привилегий",
     "short_description": "Тестирование возможности повышения уровня доступа в системе.",
     "goal": "Выявить возможности горизонтального и вертикального повышения привилегий."},
    {"check_id": "WSTG-ATHZ-04", "category": "Authorization",
     "name": "Небезопасные прямые ссылки на объекты",
     "short_description": "Тестирование на уязвимости IDOR для доступа к чужим данным.",
     "goal": "Проверить возможность доступа к объектам других пользователей через подмену идентификаторов."},

    # ── SESS: Session Management ──
    {"check_id": "WSTG-SESS-01", "category": "Session Management",
     "name": "Проверка схемы управления сессиями",
     "short_description": "Анализ механизма создания и управления идентификаторами сессий.",
     "goal": "Оценить надёжность и непредсказуемость схемы управления сессиями."},
    {"check_id": "WSTG-SESS-02", "category": "Session Management",
     "name": "Проверка атрибутов cookie",
     "short_description": "Анализ атрибутов безопасности cookie (Secure, HttpOnly, SameSite).",
     "goal": "Убедиться в корректной настройке защитных атрибутов cookie."},
    {"check_id": "WSTG-SESS-03", "category": "Session Management",
     "name": "Проверка фиксации сессии",
     "short_description": "Тестирование на уязвимость фиксации идентификатора сессии.",
     "goal": "Выявить возможность навязывания известного идентификатора сессии."},
    {"check_id": "WSTG-SESS-04", "category": "Session Management",
     "name": "Проверка раскрытия переменных сессии",
     "short_description": "Тестирование на утечку данных сессии через URL, логи и кеш.",
     "goal": "Обнаружить раскрытие идентификаторов сессии через небезопасные каналы."},
    {"check_id": "WSTG-SESS-05", "category": "Session Management",
     "name": "Проверка на CSRF",
     "short_description": "Тестирование защиты от межсайтовой подделки запросов.",
     "goal": "Выявить отсутствие или обход защиты от CSRF-атак."},
    {"check_id": "WSTG-SESS-06", "category": "Session Management",
     "name": "Проверка функции выхода",
     "short_description": "Тестирование корректности завершения пользовательских сессий.",
     "goal": "Убедиться в полной инвалидации сессии при выходе из системы."},
    {"check_id": "WSTG-SESS-07", "category": "Session Management",
     "name": "Проверка таймаута сессии",
     "short_description": "Тестирование автоматического завершения неактивных сессий.",
     "goal": "Проверить наличие и корректность таймаута бездействия сессии."},
    {"check_id": "WSTG-SESS-08", "category": "Session Management",
     "name": "Проверка перегрузки переменных сессии",
     "short_description": "Тестирование на перезапись переменных сессии через манипуляции.",
     "goal": "Выявить возможность изменения атрибутов сессии через повторное использование переменных."},
    {"check_id": "WSTG-SESS-09", "category": "Session Management",
     "name": "Проверка перехвата сессии",
     "short_description": "Тестирование возможности кражи или перехвата идентификатора сессии.",
     "goal": "Оценить устойчивость механизма сессий к перехвату и воспроизведению."},

    # ── INPV: Input Validation ──
    {"check_id": "WSTG-INPV-01", "category": "Input Validation",
     "name": "Отражённый межсайтовый скриптинг",
     "short_description": "Тестирование на reflected XSS через пользовательский ввод.",
     "goal": "Выявить возможность внедрения скриптов через отражённые параметры."},
    {"check_id": "WSTG-INPV-02", "category": "Input Validation",
     "name": "Хранимый межсайтовый скриптинг",
     "short_description": "Тестирование на stored XSS через сохраняемые данные.",
     "goal": "Обнаружить возможность постоянного внедрения скриптов в хранимые данные."},
    {"check_id": "WSTG-INPV-03", "category": "Input Validation",
     "name": "Подмена HTTP-глаголов",
     "short_description": "Тестирование обхода контроля доступа через подмену HTTP-методов.",
     "goal": "Выявить возможность обхода ограничений через изменение HTTP-метода запроса."},
    {"check_id": "WSTG-INPV-04", "category": "Input Validation",
     "name": "Загрязнение HTTP-параметров",
     "short_description": "Тестирование на уязвимость HTTP Parameter Pollution.",
     "goal": "Проверить поведение приложения при передаче дублирующихся параметров."},
    {"check_id": "WSTG-INPV-05", "category": "Input Validation",
     "name": "SQL-инъекция",
     "short_description": "Тестирование на внедрение SQL-кода через пользовательский ввод.",
     "goal": "Выявить точки внедрения SQL-кода для несанкционированного доступа к данным."},
    {"check_id": "WSTG-INPV-06", "category": "Input Validation",
     "name": "LDAP-инъекция",
     "short_description": "Тестирование на внедрение LDAP-запросов через входные данные.",
     "goal": "Обнаружить возможность манипуляции LDAP-запросами через пользовательский ввод."},
    {"check_id": "WSTG-INPV-07", "category": "Input Validation",
     "name": "XML-инъекция",
     "short_description": "Тестирование на внедрение вредоносных XML-данных.",
     "goal": "Выявить уязвимости обработки XML, включая XXE-атаки."},
    {"check_id": "WSTG-INPV-08", "category": "Input Validation",
     "name": "SSI-инъекция",
     "short_description": "Тестирование на внедрение директив Server-Side Includes.",
     "goal": "Проверить возможность выполнения SSI-директив через пользовательский ввод."},
    {"check_id": "WSTG-INPV-09", "category": "Input Validation",
     "name": "XPath-инъекция",
     "short_description": "Тестирование на внедрение XPath-выражений.",
     "goal": "Обнаружить возможность манипуляции XPath-запросами к XML-данным."},
    {"check_id": "WSTG-INPV-10", "category": "Input Validation",
     "name": "Инъекция в IMAP/SMTP",
     "short_description": "Тестирование на внедрение команд в почтовые протоколы.",
     "goal": "Выявить возможность инъекции команд IMAP/SMTP через входные параметры."},
    {"check_id": "WSTG-INPV-11", "category": "Input Validation",
     "name": "Инъекция кода",
     "short_description": "Тестирование на внедрение и выполнение произвольного кода.",
     "goal": "Проверить возможность выполнения произвольного кода на стороне сервера."},
    {"check_id": "WSTG-INPV-12", "category": "Input Validation",
     "name": "Инъекция команд ОС",
     "short_description": "Тестирование на внедрение системных команд через ввод данных.",
     "goal": "Выявить возможность выполнения произвольных команд операционной системы."},
    {"check_id": "WSTG-INPV-13", "category": "Input Validation",
     "name": "Инъекция форматной строки",
     "short_description": "Тестирование на уязвимости форматных строк.",
     "goal": "Обнаружить возможность эксплуатации функций форматирования строк."},
    {"check_id": "WSTG-INPV-14", "category": "Input Validation",
     "name": "Инкубированная уязвимость",
     "short_description": "Тестирование на уязвимости с отложенным срабатыванием.",
     "goal": "Выявить уязвимости, которые проявляются не сразу, а при последующей обработке данных."},
    {"check_id": "WSTG-INPV-15", "category": "Input Validation",
     "name": "HTTP Splitting/Smuggling",
     "short_description": "Тестирование на атаки разделения и контрабанды HTTP-запросов.",
     "goal": "Проверить устойчивость к манипуляциям с HTTP-заголовками и телом запроса."},
    {"check_id": "WSTG-INPV-16", "category": "Input Validation",
     "name": "Проверка входящих HTTP-запросов",
     "short_description": "Анализ обработки нестандартных и вредоносных HTTP-запросов.",
     "goal": "Оценить корректность валидации входящих HTTP-запросов приложением."},
    {"check_id": "WSTG-INPV-17", "category": "Input Validation",
     "name": "Инъекция заголовка Host",
     "short_description": "Тестирование на манипуляцию заголовком Host в HTTP-запросах.",
     "goal": "Выявить уязвимости, связанные с доверием к значению заголовка Host."},
    {"check_id": "WSTG-INPV-18", "category": "Input Validation",
     "name": "Серверная инъекция шаблонов (SSTI)",
     "short_description": "Тестирование на внедрение кода в серверные шаблонизаторы.",
     "goal": "Обнаружить возможность выполнения кода через инъекцию в шаблоны."},
    {"check_id": "WSTG-INPV-19", "category": "Input Validation",
     "name": "Подделка серверных запросов (SSRF)",
     "short_description": "Тестирование на возможность отправки запросов от имени сервера.",
     "goal": "Выявить возможность выполнения запросов к внутренним ресурсам через сервер."},

    # ── ERRH: Error Handling ──
    {"check_id": "WSTG-ERRH-01", "category": "Error Handling",
     "name": "Проверка обработки ошибок",
     "short_description": "Анализ сообщений об ошибках на предмет утечки информации.",
     "goal": "Выявить раскрытие конфиденциальных данных через сообщения об ошибках."},
    {"check_id": "WSTG-ERRH-02", "category": "Error Handling",
     "name": "Проверка трассировки стека",
     "short_description": "Тестирование на раскрытие стека вызовов в ответах приложения.",
     "goal": "Обнаружить утечку технических деталей через трассировки стека."},

    # ── CRYP: Cryptography ──
    {"check_id": "WSTG-CRYP-01", "category": "Cryptography",
     "name": "Проверка безопасности транспортного уровня",
     "short_description": "Тестирование конфигурации TLS/SSL и сертификатов.",
     "goal": "Убедиться в надёжной настройке шифрования транспортного уровня."},
    {"check_id": "WSTG-CRYP-02", "category": "Cryptography",
     "name": "Проверка на Padding Oracle",
     "short_description": "Тестирование на уязвимость Padding Oracle в криптографии.",
     "goal": "Выявить возможность расшифровки данных через атаку Padding Oracle."},
    {"check_id": "WSTG-CRYP-03", "category": "Cryptography",
     "name": "Передача данных по незашифрованным каналам",
     "short_description": "Проверка передачи конфиденциальных данных без шифрования.",
     "goal": "Обнаружить отправку чувствительных данных по незащищённым каналам."},
    {"check_id": "WSTG-CRYP-04", "category": "Cryptography",
     "name": "Проверка слабого шифрования",
     "short_description": "Анализ используемых криптографических алгоритмов на устойчивость.",
     "goal": "Выявить использование устаревших или слабых алгоритмов шифрования."},

    # ── BUSL: Business Logic ──
    {"check_id": "WSTG-BUSL-01", "category": "Business Logic",
     "name": "Проверка валидации бизнес-данных",
     "short_description": "Тестирование корректности проверки данных на бизнес-уровне.",
     "goal": "Выявить отсутствие валидации данных в контексте бизнес-логики."},
    {"check_id": "WSTG-BUSL-02", "category": "Business Logic",
     "name": "Проверка возможности подделки запросов",
     "short_description": "Тестирование на подделку и манипуляцию бизнес-запросами.",
     "goal": "Обнаружить возможность создания поддельных запросов, нарушающих бизнес-логику."},
    {"check_id": "WSTG-BUSL-03", "category": "Business Logic",
     "name": "Проверка целостности данных",
     "short_description": "Тестирование контроля целостности данных в бизнес-процессах.",
     "goal": "Выявить отсутствие проверок целостности данных при обработке."},
    {"check_id": "WSTG-BUSL-04", "category": "Business Logic",
     "name": "Проверка временных ограничений процессов",
     "short_description": "Тестирование зависимости бизнес-логики от временных параметров.",
     "goal": "Обнаружить уязвимости, связанные с условиями гонки и таймингом операций."},
    {"check_id": "WSTG-BUSL-05", "category": "Business Logic",
     "name": "Проверка лимитов использования функций",
     "short_description": "Тестирование ограничений на количество вызовов операций.",
     "goal": "Выявить отсутствие лимитов на повторное использование функций."},
    {"check_id": "WSTG-BUSL-06", "category": "Business Logic",
     "name": "Проверка обхода рабочих процессов",
     "short_description": "Тестирование возможности пропуска шагов в бизнес-процессах.",
     "goal": "Обнаружить возможность обхода обязательных этапов workflow."},
    {"check_id": "WSTG-BUSL-07", "category": "Business Logic",
     "name": "Проверка защиты от злоупотребления приложением",
     "short_description": "Тестирование защитных мер против нецелевого использования функций.",
     "goal": "Оценить наличие защиты от злоупотребления легитимными функциями."},
    {"check_id": "WSTG-BUSL-08", "category": "Business Logic",
     "name": "Проверка загрузки неожиданных типов файлов",
     "short_description": "Тестирование валидации типов загружаемых файлов.",
     "goal": "Выявить возможность загрузки файлов неразрешённых типов."},
    {"check_id": "WSTG-BUSL-09", "category": "Business Logic",
     "name": "Проверка загрузки вредоносных файлов",
     "short_description": "Тестирование возможности загрузки файлов с вредоносным содержимым.",
     "goal": "Обнаружить возможность загрузки и выполнения вредоносных файлов."},

    # ── CLNT: Client-side ──
    {"check_id": "WSTG-CLNT-01", "category": "Client-side",
     "name": "DOM-based XSS",
     "short_description": "Тестирование на межсайтовый скриптинг через DOM-модель.",
     "goal": "Выявить возможность внедрения скриптов через манипуляцию DOM."},
    {"check_id": "WSTG-CLNT-02", "category": "Client-side",
     "name": "Выполнение JavaScript",
     "short_description": "Тестирование на внедрение и выполнение JavaScript-кода.",
     "goal": "Обнаружить возможность выполнения произвольного JavaScript на стороне клиента."},
    {"check_id": "WSTG-CLNT-03", "category": "Client-side",
     "name": "HTML-инъекция",
     "short_description": "Тестирование на внедрение произвольной HTML-разметки.",
     "goal": "Выявить возможность внедрения HTML-кода для подмены содержимого страницы."},
    {"check_id": "WSTG-CLNT-04", "category": "Client-side",
     "name": "Открытое перенаправление на стороне клиента",
     "short_description": "Тестирование на уязвимость открытого редиректа через клиентский код.",
     "goal": "Обнаружить возможность перенаправления пользователя на вредоносный сайт."},
    {"check_id": "WSTG-CLNT-05", "category": "Client-side",
     "name": "CSS-инъекция",
     "short_description": "Тестирование на внедрение произвольных CSS-стилей.",
     "goal": "Выявить возможность манипуляции отображением страницы через CSS-инъекцию."},
    {"check_id": "WSTG-CLNT-06", "category": "Client-side",
     "name": "Манипуляция клиентскими ресурсами",
     "short_description": "Тестирование на подмену ресурсов, загружаемых клиентом.",
     "goal": "Обнаружить возможность подмены внешних ресурсов приложения."},
    {"check_id": "WSTG-CLNT-07", "category": "Client-side",
     "name": "Проверка CORS",
     "short_description": "Тестирование настройки Cross-Origin Resource Sharing.",
     "goal": "Выявить небезопасную конфигурацию политики совместного использования ресурсов."},
    {"check_id": "WSTG-CLNT-08", "category": "Client-side",
     "name": "Межсайтовые Flash-уязвимости",
     "short_description": "Тестирование Flash-контента на кросс-доменные уязвимости.",
     "goal": "Обнаружить уязвимости в Flash-объектах, допускающие межсайтовые атаки."},
    {"check_id": "WSTG-CLNT-09", "category": "Client-side",
     "name": "Кликджекинг",
     "short_description": "Тестирование защиты от встраивания страницы во фреймы.",
     "goal": "Выявить возможность проведения атаки кликджекинга через iframe."},
    {"check_id": "WSTG-CLNT-10", "category": "Client-side",
     "name": "Проверка WebSockets",
     "short_description": "Тестирование безопасности WebSocket-соединений.",
     "goal": "Оценить защищённость механизма WebSocket-коммуникации."},
    {"check_id": "WSTG-CLNT-11", "category": "Client-side",
     "name": "Проверка Web Messaging",
     "short_description": "Тестирование безопасности механизма postMessage.",
     "goal": "Выявить небезопасное использование API Web Messaging между окнами."},
    {"check_id": "WSTG-CLNT-12", "category": "Client-side",
     "name": "Проверка хранилища браузера",
     "short_description": "Тестирование безопасности localStorage, sessionStorage и IndexedDB.",
     "goal": "Обнаружить хранение конфиденциальных данных в клиентском хранилище."},
    {"check_id": "WSTG-CLNT-13", "category": "Client-side",
     "name": "Межсайтовое включение скриптов (XSSI)",
     "short_description": "Тестирование на утечку данных через подключение скриптов с другого домена.",
     "goal": "Выявить возможность кражи данных через включение скриптов сторонним сайтом."},
]


def get_checklist_items(report_type: str) -> list[dict]:
    checklist_type = CHECKLIST_MAP.get(report_type)
    if checklist_type is None:
        return []
    if checklist_type == "wstg":
        return [{"checklist_type": "wstg", **item} for item in _WSTG_ITEMS]
    return []
