CHECKLIST_MAP: dict[str, str] = {
    "web": "wstg",
    "ios": "mstg_ios",
    "android": "mstg_android",
    "iot": "istg",
    "ai": "aitg",
}


_WSTG_ITEMS = [
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-01",
        "category": "Information Gathering",
        "name": "Разведка в поисковых системах и обнаружение утечек информации",
        "short_description": "",
        "goal": "- Определить, какая конфиденциальная информация об архитектуре и конфигурации приложения, системы или организации раскрывается прямо (на сайте организации) или косвенно (через сторонние сервисы).",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-02",
        "category": "Information Gathering",
        "name": "Определение web-сервера",
        "short_description": "",
        "goal": "- Определить версию и тип используемого web-сервера, чтобы на их основе провести обнаружение известных уязвимостей.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-03",
        "category": "Information Gathering",
        "name": "Анализ метафайлов web-сервера на предмет утечки информации",
        "short_description": "",
        "goal": "- Выявить скрытые или неочевидные пути и функциональные возможности приложения с помощью анализа файлов метаданных.\n- Извлечь и отобразить на схеме эту и другую информацию, которая может привести к лучшему пониманию исследуемых систем.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-04",
        "category": "Information Gathering",
        "name": "Инвентаризация приложений на web-сервере",
        "short_description": "",
        "goal": "- Провести инвентаризацию приложений, которые находятся на web-сервере и входят в область исследования.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-05",
        "category": "Information Gathering",
        "name": "Анализ контента web-страницы на предмет утечки информации",
        "short_description": "",
        "goal": "- Просмотреть комментарии в разметке web-страниц, метаданные и страницы перенаправления, чтобы обнаружить утечки информации.\n- Собрать файлы JavaScript и просмотреть их код, чтобы лучше понять приложение и найти возможные утечки информации.\n- Определить наличие в рабочей среде Source Map или других файлов отладки.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-06",
        "category": "Information Gathering",
        "name": "Определение точек входа в приложение",
        "short_description": "",
        "goal": "- Определить возможные точки входа и инъекции в приложение с помощью анализа запросов и ответов.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-07",
        "category": "Information Gathering",
        "name": "Пути выполнения приложения",
        "short_description": "",
        "goal": "- Составить карту связей целевого приложения и определить основные информационные потоки",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INFO-08",
        "category": "Information Gathering",
        "name": "Определение фреймворка web-приложения",
        "short_description": "",
        "goal": "- Определить компоненты, используемые web-приложениями.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-01",
        "category": "Configuration and Deployment Management",
        "name": "Анализ конфигурации сетевой инфраструктуры",
        "short_description": "",
        "goal": "- Проанализировать конфигурации приложений, развёрнутых в сети, и убедиться, что в них нет известных уязвимостей.\n- Убедиться, что используемые фреймворки и платформы безопасны и не подвержены известным уязвимостям из-за неподдерживаемого программного обеспечения или установленных по умолчанию настроек и учётных данных.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-02",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование конфигурации платформы приложения",
        "short_description": "",
        "goal": "- Убедиться, что удалены все известные ненужные файлы и изменены значения по умолчанию.\n- Убедиться, что в рабочей среде не осталось отладочного кода и отключены инструменты для отладки.\n- Проанализировать механизмы ведения журнала событий, установленные для приложения.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-03",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование обработки расширений файлов на наличие чувствительной информации",
        "short_description": "",
        "goal": "- Проанализировать чувствительные расширения файлов или расширения, которые могут содержать «сырые» данные (например, скрипты, учётные данные и т.д.).\n- Убедиться, что в наборе правил нет обхода системной платформы.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-04",
        "category": "Configuration and Deployment Management",
        "name": "Анализ старых резервных копий и файлов без ссылок",
        "short_description": "",
        "goal": "- Найти и проанализировать файлы без ссылок, которые могут содержать конфиденциальную информацию.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-05",
        "category": "Configuration and Deployment Management",
        "name": "Инвентаризация интерфейсов администрирования для инфраструктуры и для приложений",
        "short_description": "",
        "goal": "- Найти скрытые интерфейсы администратора и определить их функциональные возможности.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-06",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование методов HTTP",
        "short_description": "",
        "goal": "-Определить поддерживаемые HTTP-методы.\n-Протестировать обход контроля доступа.\n- Протестировать способы переопределения HTTP-методов.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-07",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование HTTP Strict Transport Security",
        "short_description": "",
        "goal": "- Проанализировать наличие заголовка HSTS и убедиться в его работоспособности.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-08",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование междоменной политики для RIA",
        "short_description": "",
        "goal": "- Проанализировать и подтвердить настройки в файлах политик.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-09",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование разрешений на доступ к файлам",
        "short_description": "",
        "goal": "- Проанализировать и выявить возможности несанкционированного доступа к файлам.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-10",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование на захват поддомена",
        "short_description": "",
        "goal": "- Проинвентаризировать все возможные домены (бывшие и действующие).\n- Выявить забытые или некорректно настроенные домены.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-11",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование облачного хранилища",
        "short_description": "",
        "goal": "- Убедиться в корректности настроек конфигурации контроля доступа для служб хранения.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CONF-12",
        "category": "Configuration and Deployment Management",
        "name": "Тестирование Content Security Policy",
        "short_description": "",
        "goal": "- Проанализировать наличие заголовка Content-Security-Policy или одноимённого элемента <meta>, чтобы определить некорректные конфигурации.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-IDNT-01",
        "category": "Identity Management Testing",
        "name": "Тестирование определения ролей",
        "short_description": "",
        "goal": "- Определить и задокументировать роли, используемые приложением.\n- Попытаться переключиться, изменить или получить доступ к другой роли.\n- Проанализировать состав ролей и потребности, лежащие в основе предоставленных разрешений.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-IDNT-02",
        "category": "Identity Management Testing",
        "name": "Тестирование процесса регистрации пользователя",
        "short_description": "",
        "goal": "- Убедиться, что требования к идентификации при регистрации пользователей соответствуют бизнес-требованиям и требованиям безопасности.\n- Убедиться в безопасность процесса регистрации пользователей.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-IDNT-03",
        "category": "Identity Management Testing",
        "name": "Тестирование процесса создания учётных записей",
        "short_description": "",
        "goal": "- Проанализировать, какие пользователи могут создавать учётные записи для других и какого типа.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-IDNT-04",
        "category": "Identity Management Testing",
        "name": "Перебор и угадывание учётных записей пользователей",
        "short_description": "",
        "goal": "- Проанализировать процессы, относящиеся к идентификации пользователя (например, регистрация пользователя, вход в систему и т.д.).\n- Где это возможно, найти учётные записи пользователей, анализируя ответы.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-IDNT-05",
        "category": "Identity Management Testing",
        "name": "Тестирование политики в отношении имён пользователей",
        "short_description": "",
        "goal": "- Определить, делает ли следование структуре имени учётной записи приложение уязвимым для перебора учётных записей.\n- Определить, разрешён ли перебор учётных записей через сообщения об ошибках.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-02",
        "category": "Authentication Testing",
        "name": "Тестирование учётных данных по умолчанию",
        "short_description": "",
        "goal": "- Определить, есть ли в приложении какие-либо учётные записи пользователей с паролями по умолчанию.\n- Проанализировать, не создаются ли новые учётные записи пользователей со слабыми или предсказуемыми паролями.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-03",
        "category": "Authentication Testing",
        "name": "Тестирование механизма блокировки",
        "short_description": "",
        "goal": "- Оценить способность механизмов блокировки учётных записей противостоять возможности подбора пароля методом перебора.\n- Оценить устойчивость механизма разблокировки к несанкционированной разблокировке учётной записи.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-04",
        "category": "Authentication Testing",
        "name": "Тестирование обхода схемы аутентификации",
        "short_description": "",
        "goal": "- Убедиться, что аутентификация применяется ко всем службам, которым она требуется.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-05",
        "category": "Authentication Testing",
        "name": "Тестирование уязвимого запоминания пароля",
        "short_description": "",
        "goal": "- Убедиться, что сгенерированная сессия безопасна и не подвергает опасности учётные данные пользователя.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-06",
        "category": "Authentication Testing",
        "name": "Тестирование на уязвимости кэша браузера",
        "short_description": "",
        "goal": "- Проанализировать, не хранит ли приложение конфиденциальную информацию на стороне клиента.\n- Проверить, возможен ли доступ к ней без авторизации.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-07",
        "category": "Authentication Testing",
        "name": "Тестирование парольной политики",
        "short_description": "",
        "goal": "- Определить устойчивость приложения к подбору паролей методом перебора с использованием доступных словарей паролей, оценив требования к их длине, сложности, повторному использованию и устареванию.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-08",
        "category": "Authentication Testing",
        "name": "Тестирование ответа на контрольный вопрос",
        "short_description": "",
        "goal": "- Определить сложность вопросов и насколько они прямолинейны.\n- Оценить возможные ответы пользователей и возможности их подбора.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-09",
        "category": "Authentication Testing",
        "name": "Тестирование функций изменения или сброса пароля",
        "short_description": "",
        "goal": "- Определить, позволяют ли функции смены и сброса пароля компрометировать учётные записи.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHN-10",
        "category": "Authentication Testing",
        "name": "Тестирование аутентификации в альтернативных каналах",
        "short_description": "",
        "goal": "- Определить альтернативные каналы аутентификации.\n- Оценить применяющиеся меры защиты и наличие обходных путей по альтернативным каналам.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-AUTH-11",
        "category": "Authentication Testing",
        "name": "Тестирование мультифакторной аутентификации (MFA)",
        "short_description": "",
        "goal": "- Определить тип МФА, используемой приложением.\n- Определить насколько надёжна и безопасна реализация МФА.\n- Попытаться обойти МФА.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-01",
        "category": "Authorization Testing",
        "name": "Тестирование включения файлов при обходе каталогов",
        "short_description": "",
        "goal": "- Определить точки инъекции, доступные при обходе пути.\n- Оценить методы обхода и определить глубину обхода пути.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-02",
        "category": "Authorization Testing",
        "name": "Тестирование обхода схемы авторизации",
        "short_description": "",
        "goal": "- Оценить, возможен ли горизонтальный или вертикальный доступ.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-03",
        "category": "Authorization Testing",
        "name": "Тестирование повышения привилегий",
        "short_description": "",
        "goal": "- Определить точки входа, связанные с манипулированием привилегиями.\n- Пофаззить или иным образом попытаться обойти меры защиты.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-04",
        "category": "Authorization Testing",
        "name": "Тестирование небезопасных прямых ссылок на объекты (IDOR)",
        "short_description": "",
        "goal": "- Найти точки с прямыми ссылками на объекты.\n- Оценить меры контроля доступа и их уязвимость для IDOR.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-05",
        "category": "Authorization Testing",
        "name": "Тестирование уязвимостей в Oauth",
        "short_description": "",
        "goal": "- Определить, является ли реализация OAuth2 уязвимой, устаревшей или нестандартной.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-05.1",
        "category": "Authorization Testing",
        "name": "Тестирование уязвимостей сервера авторизации Oauth",
        "short_description": "",
        "goal": "Найти уязвимости в сервере авторизации",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ATHZ-05.2",
        "category": "Authorization Testing",
        "name": "Тестирование уязвимостей клиента Oauth",
        "short_description": "",
        "goal": "Найти уязвимости клиента Oauth",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-01",
        "category": "Session Management Testing",
        "name": "Тестирование схемы управления сессиями",
        "short_description": "",
        "goal": "- Собрать сессионные токены для одного пользователя, и по возможности для разных пользователей.\n- Проанализировать их, чтобы убедиться, что обеспечивается их достаточная случайность, чтобы предотвратить атаки подмены сессии.\n- Модифицировать cookie, которые не подписаны и содержат информацию, которой можно манипулировать.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-02",
        "category": "Session Management Testing",
        "name": "Тестирование атрибутов Cookie",
        "short_description": "",
        "goal": "- Убедитесь, что для cookie установлена безопасная конфигурация.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-03",
        "category": "Session Management Testing",
        "name": "Тестирование фиксации сессии",
        "short_description": "",
        "goal": "- Проанализировать механизм и процедуру аутентификации.\n- Принудительно использовать cookie и оценить результат.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-04",
        "category": "Session Management Testing",
        "name": "Тестирование незащищённых параметров сессии",
        "short_description": "",
        "goal": "- Убедиться, что реализовано надлежащее шифрование.\n- Проанализировать настройки кэширования.\n- Оценить защиту канала передачи и HTTP-методов.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-05",
        "category": "Session Management Testing",
        "name": "Тестирование подделки межсайтовых запросов (CSRF)",
        "short_description": "",
        "goal": "- Определить, можно ли инициировать запросы от имени пользователя, которые не были инициированы этим пользователем.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-06",
        "category": "Session Management Testing",
        "name": "Тестирование выхода из системы",
        "short_description": "",
        "goal": "- Оценить пользовательский интерфейс выхода из системы.\n- Проанализировать тайм-аут сессии и правильно ли она завершается после выхода из приложения.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-07",
        "category": "Session Management Testing",
        "name": "Тестирование тайм-аута сессии",
        "short_description": "",
        "goal": "- Убедиться, что установлен жёсткий тайм-аут сессии.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-08",
        "category": "Session Management Testing",
        "name": "Тестирование «пазла» сессии",
        "short_description": "",
        "goal": "- Определить все переменные сессии.\n- Нарушить логику процесса создания сессии.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-09",
        "category": "Session Management Testing",
        "name": "Тестирование перехвата сессии",
        "short_description": "",
        "goal": "- Найти уязвимые сессионные cookie.\n- Перехватить уязвимые cookie и оценить уровень риска.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-SESS-10",
        "category": "Session Management Testing",
        "name": "Тестирование JSON Web Token (JWT)",
        "short_description": "",
        "goal": "- Определить, раскрывают ли JWT чувствительную информацию.\n- Определить, можно ли подделать или модифицировать JWT.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-01",
        "category": "Input Validation Testing",
        "name": "Тестирование отражённых межсайтовых скриптов (Reflected XSS)",
        "short_description": "",
        "goal": "- Определить переменные, которые отражаются в ответах.\n- Оценить входные данные, которые им присваиваются, и кодировку применяемую в ответе (если указана).",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-02",
        "category": "Input Validation Testing",
        "name": "Тестирование хранимых межсайтовых скриптов (Stored XSS)",
        "short_description": "",
        "goal": "- Выявить хранимые входные данные, которые отражаются на стороне клиента.\n- Оценить входные данные, которые он принимает, и кодировку, которая применяется при возврате (при наличии).",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-04",
        "category": "Input Validation Testing",
        "name": "Тестирование «загрязнения» HTTP-параметров (HPP)",
        "short_description": "",
        "goal": "- Определить бэкенд и используемый метод парсинга.\n- Оценить точки инъекции и попытаться обойти входные фильтры с помощью HPP.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05",
        "category": "Input Validation Testing",
        "name": "Тестирование SQL-инъекций (SQLi)",
        "short_description": "",
        "goal": "- Найти точки инъекции SQL.\n- Оценить воздействие инъекции и уровень доступа, который может быть получен с её помощью.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.1",
        "category": "Input Validation Testing",
        "name": "Тестирование Oracle",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.2",
        "category": "Input Validation Testing",
        "name": "Тестирование MySQL",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.3",
        "category": "Input Validation Testing",
        "name": "Тестирование MS SQL Server",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.4",
        "category": "Input Validation Testing",
        "name": "Тестирование PostgreSQL",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.5",
        "category": "Input Validation Testing",
        "name": "Тестирование MS Access",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.6",
        "category": "Input Validation Testing",
        "name": "Тестирование NoSQL-инъекций",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.7",
        "category": "Input Validation Testing",
        "name": "Тестирование ORM-инъекций",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-05.8",
        "category": "Input Validation Testing",
        "name": "Тестирование на стороне клиента",
        "short_description": "",
        "goal": "",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-06",
        "category": "Input Validation Testing",
        "name": "Тестирование LDAP-инъекций",
        "short_description": "",
        "goal": "- Определить точки инъекции LDAP.\n- Оценить воздействие инъекции.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-07",
        "category": "Input Validation Testing",
        "name": "Тестирование XML-инъекций",
        "short_description": "",
        "goal": "- Определить точки входа для XML-инъекций.\n-Оценить типы атак, которые можно провести, и степень их воздействия.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-08",
        "category": "Input Validation Testing",
        "name": "Тестирование SSI-инъекций",
        "short_description": "",
        "goal": "- Найти точки для инъекции SSI.\n- Оценить последствия от инъекции.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-09",
        "category": "Input Validation Testing",
        "name": "Тестирование Xpath-инъекций",
        "short_description": "",
        "goal": "- Найти точки для инъекции XPath.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-10",
        "category": "Input Validation Testing",
        "name": "Тестирование IMAP/SMTP-инъекций",
        "short_description": "",
        "goal": "- Найти точки для IMAP/SMTP-инъекции.\n- Разобраться в потоках информации и структуре развёртывания системы.\n- Оценить воздействие инъекций.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-11",
        "category": "Input Validation Testing",
        "name": "Тестирование инъекции кода",
        "short_description": "",
        "goal": "- Найти точки для инъекции, где вы можете вставить код в приложение.\n- Оценить воздействие инъекции.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-11.1",
        "category": "Input Validation Testing",
        "name": "Тестирование включения файлов (LFI/RFI)",
        "short_description": "",
        "goal": "- Найти точки включения файлов.\n- Оценить потенциальное воздействие уязвимостей.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-12",
        "category": "Input Validation Testing",
        "name": "Тестирование инъекции команд ОС",
        "short_description": "",
        "goal": "- Найти точки инъекции команд и оценить их последствия",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-13",
        "category": "Input Validation Testing",
        "name": "Тестирование инъекций в строке форматирования",
        "short_description": "",
        "goal": "- Оценить, не вызывает ли инъекция спецификаторов преобразования строк форматирования в контролируемые пользователем поля нежелательного поведения приложения.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-14",
        "category": "Input Validation Testing",
        "name": "Тестирование инкубационных уязвимостей",
        "short_description": "",
        "goal": "- Выявить хранимые инъекции, которым требуется этап отзыва.\n- Понять, в чём заключается этот этап отзыва.\n- Установить прослушиватели (listeners) или активировать шаг отзыва, если это возможно.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-15",
        "category": "Input Validation Testing",
        "name": "Тестирование HTTP Splitting / Smuggling",
        "short_description": "",
        "goal": "- Оценить, уязвимо ли приложение к HTTP splitting, определив, какие из возможных атак сработают.\n- Оценить, уязвима ли цепочка передачи для HTTP smuggling, и определить, какие из возможных атак сработают.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-16",
        "category": "Input Validation Testing",
        "name": "Тестирование входящих HTTP-запросов",
        "short_description": "",
        "goal": "- Отслеживать все входящие и исходящие HTTP-запросы к web-серверу, чтобы проверять подозрительные.\n- Отслеживать HTTP-трафик без изменений прокси-сервера браузера конечного пользователя или клиентского приложения.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-17",
        "category": "Input Validation Testing",
        "name": "Тестирование инъекций в заголовке Host",
        "short_description": "",
        "goal": "- Оценить, выполняется ли динамический парсинг заголовка Host в приложении.\n- Обойти меры защиты, которые полагаются на этот заголовок.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-18",
        "category": "Input Validation Testing",
        "name": "Тестирование инъекции шаблона на стороне сервера (SSTI)",
        "short_description": "",
        "goal": "- Найти уязвимые точки для инъекции шаблонов.\n- Идентифицировать используемый шаблонизатор.\n- Создать эксплойт.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-19",
        "category": "Input Validation Testing",
        "name": "Тестирование подделки запроса на стороне сервера (SSRF)",
        "short_description": "",
        "goal": "- Найти точки для инъекции SSRF.\n- Протестировать, пригодны ли эти точки для эксплуатации.\n- Оценить воздействие уязвимости.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-INPV-20",
        "category": "Input Validation Testing",
        "name": "Тестирование массового переназначения",
        "short_description": "",
        "goal": "- Найти запросы, которые изменяют объекты.\n- Оценить, можно ли изменять поля, которые никогда не предназначались для изменения извне.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-ERRH-01",
        "category": "Error Handling Testing",
        "name": "Тестирование некорректной обработки ошибок",
        "short_description": "",
        "goal": "- Найти вывод по существующим ошибкам.\n- Проанализировать различные возвращаемые выходные данные.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CRYP-01",
        "category": "Cryptography Testing",
        "name": "Тестирование безопасности транспортного уровня",
        "short_description": "",
        "goal": "- Проверить конфигурацию протокола.\n- Проанализировать криптографическую стойкость и доверие к сертификату.\n- Убедиться, что криптозащита TLS не поддаётся обходу и должным образом реализована во всём приложении.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CRYP-02",
        "category": "Cryptography Testing",
        "name": "Тестирование оракула дополнений",
        "short_description": "",
        "goal": "- Найти зашифрованные сообщения, которые полагаются на дополнение.\n- Попытаться нарушить дополнение зашифрованных сообщений и проанализировать выданные сообщения об ошибках для дальнейшего анализа.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CRYP-03",
        "category": "Cryptography Testing",
        "name": "Тестирование на наличие конфиденциальной информации, передаваемой по незашифрованным каналам",
        "short_description": "",
        "goal": "- Определить категории конфиденциальности информации, передаваемой по различным каналам.\n- Оценить степень защищённости используемых каналов.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-01",
        "category": "Business Logic Testing",
        "name": "Тестирование форматно-логического контроля данных",
        "short_description": "",
        "goal": "- Определить точки инъекции данных.\n- Убедиться, что все проверки проводятся на серверной части и их нельзя обойти.\n- Попытаться нарушить формат ожидаемых данных и проанализировать, как приложение их обрабатывает.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-02",
        "category": "Business Logic Testing",
        "name": "Тестирование способности подделывать запросы",
        "short_description": "",
        "goal": "- Проанализировать проектную документацию в поисках угадываемой, предсказуемой или скрытой функциональности полей.\n- Вставить логически допустимые данные, чтобы обойти стандартную логику бизнес-процесса.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-03",
        "category": "Business Logic Testing",
        "name": "Тестирование проверки целостности",
        "short_description": "",
        "goal": "- Проанализировать проектную документацию на компоненты системы, которые передают, хранят или обрабатывают данные.\n- Определить, какие типы данных логически приемлемы для каждого компонента, а от каких система должна защищаться.\n- Определить, кому должно быть разрешено изменять или читать эти данные в каждом компоненте.\n- Попытаться вставить, изменить или удалить значения данных, используемые каждым компонентом, которые не должны быть разрешены в соответствии с логикой бизнес-процесса.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-04",
        "category": "Business Logic Testing",
        "name": "Тестирование времени обработки",
        "short_description": "",
        "goal": "- Проанализировать проектную документацию на предмет функциональности системы, на которую может влиять время.\n- Придумать и реализовать примеры неправильного использования.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-05",
        "category": "Business Logic Testing",
        "name": "Тестирование ограничений на количество раз, которое функция может быть вызвана",
        "short_description": "",
        "goal": "- Найти функции, для которых должны быть установлены ограничения на количество раз, которое их можно вызвать.\n- Оценить, установлено ли логическое ограничение для функций и корректно ли оно контролируется.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-06",
        "category": "Business Logic Testing",
        "name": "Тестирование обхода потока операций",
        "short_description": "",
        "goal": "- Проанализировать проектную документацию, чтобы найти способы пропустить или выполнить этапы процесса в порядке, отличном от предполагаемой приложением логики потока операций.\n- Разработать сценарии нецелевого использования и попытаться обойти каждый найденный поток операций.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-07",
        "category": "Business Logic Testing",
        "name": "Тестирование защиты от нецелевого использования приложений",
        "short_description": "",
        "goal": "- Писать заметки обо всех тестах, проводимых с системой.\n- Проверить, для каких тестов в результате фаззинга функциональность отличалась от целевой.\n- Изучить существующие меры защиты и проверить, достаточно ли их для защиты системы от методов обхода.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-08",
        "category": "Business Logic Testing",
        "name": "Тестирование загрузки файлов непредусмотренных типов",
        "short_description": "",
        "goal": "- Проанализировать проектную документацию на наличие типов файлов, которые отклоняются системой.\n- Убедиться, что непредусмотренные типы файлов отклоняются и обрабатываются безопасно.\n- Убедиться, что пакетная загрузка файлов безопасна и не допускает обхода установленных мер защиты.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-09",
        "category": "Business Logic Testing",
        "name": "Тестирование загрузки вредоносных файлов",
        "short_description": "",
        "goal": "- Найти функцию загрузки файлов.\n- Проанализировать документацию по проекту, чтобы определить, какие типы файлов считаются приемлемыми, а какие — опасными или вредоносными.\n- Если документация недоступна, то определить, что было бы уместно, исходя из назначения приложения.\n- Определить, как обрабатываются загруженные файлы.\n- Найти или создать набор вредоносных файлов для тестирования.\n- Попробовать загрузить вредоносные файлы в приложение и определить, принимаются ли, и обрабатываются ли они.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-BUSL-10",
        "category": "Business Logic Testing",
        "name": "Тестирование платёжных функций",
        "short_description": "",
        "goal": "- Определить, надёжна ли бизнес-логика для функций электронной коммерции.\n- Понять, как работают функции оплаты.\n- Определить, защищены ли платёжные функции.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-01",
        "category": "Client-side Testing",
        "name": "Тестирование межсайтового скриптинга на основе DOM",
        "short_description": "",
        "goal": "- Найти приёмники DOM.\n- Составить полезные нагрузки для каждого типа приёмника.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-01.1",
        "category": "Client-side Testing",
        "name": "Тестирование самостоятельного межсайтового скриптинга на основе DOM",
        "short_description": "",
        "goal": "- то же, что и выше +\n- Проверить журнал ошибок в Инструментах разработчика браузера, чтобы увидеть результат и сделать выводы.\n- Проверить, сможет ли злоумышленник убедить пользователя вставить полезную нагрузку, не требуя серьёзных технических знаний.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-02",
        "category": "Client-side Testing",
        "name": "Тестирование выполнения JavaScript",
        "short_description": "",
        "goal": "- Найти приёмники и возможные точки инъекции JavaScript.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-03",
        "category": "Client-side Testing",
        "name": "Тестирование HTML-инъекции",
        "short_description": "",
        "goal": "- Найти точки инъекции HTML и оценить возможные последствия от вставленного контента.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-04",
        "category": "Client-side Testing",
        "name": "Тестирование перенаправления URL на стороне клиента",
        "short_description": "",
        "goal": "- Найти точки инъекции, которые обрабатывают URL или пути.\n- Подумать, куда система могла бы отсюда перенаправить.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-05",
        "category": "Client-side Testing",
        "name": "Тестирование CSS-инъекций",
        "short_description": "",
        "goal": "- Найти точки инъекции CSS.\n- Оценить воздействие инъекции.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-06",
        "category": "Client-side Testing",
        "name": "Тестирование манипулирования ресурсами на стороне клиента",
        "short_description": "",
        "goal": "- Найти приёмники с недостаточной проверкой входных данных.\n- Оценить влияние манипуляций с ресурсами.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-07",
        "category": "Client-side Testing",
        "name": "Тестирование Cross Origin Resource Sharing (CORS)",
        "short_description": "",
        "goal": "- Найти точки входа, реализующие CORS.\n- Убедиться, что конфигурация CORS безопасна.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-08",
        "category": "Client-side Testing",
        "name": "Тестирование межсайтовых Flash",
        "short_description": "",
        "goal": "- Декомпилировать и проанализировать код приложения.\n- Оценить входные данные приёмников и небезопасное использование методов.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-09",
        "category": "Client-side Testing",
        "name": "Тестирование перехвата клика",
        "short_description": "",
        "goal": "- Ознакомиться с имеющимися мерами защиты.\n- Оценить, насколько строги эти меры и можно ли их обойти.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-10",
        "category": "Client-side Testing",
        "name": "Тестирование WebSockets",
        "short_description": "",
        "goal": "- Определить, что используются WebSockets.\n- Оценить реализацию протокола, используя те же тесты, что и на обычных HTTP-каналах.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-11",
        "category": "Client-side Testing",
        "name": "Тестирование обмена web-сообщениями",
        "short_description": "",
        "goal": "- Оценить безопасность отправителя сообщения.\n- Убедиться, что он применяет безопасные методы и контролирует передаваемые данные.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-12",
        "category": "Client-side Testing",
        "name": "Тестирование хранилищ браузера",
        "short_description": "",
        "goal": "- Выяснить, хранит ли web-сайт чувствительные данные в хранилище на стороне клиента.\n- Проверить обработку в коде объектов хранилища на наличие возможностей атак инъекции, таких как использование непроверенных входных данных или уязвимых библиотек.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-13",
        "category": "Client-side Testing",
        "name": "Тестирование включения межсайтовых скриптов (XSSI)",
        "short_description": "",
        "goal": "- Найти в системе чувствительные данные.\n- Оценить возможность их утечки с помощью различных методов.",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-CLNT-14",
        "category": "Client-side Testing",
        "name": "Тестирование Reverse Tabnabbing",
        "short_description": "",
        "goal": "- Проверить HTML-код приложения, используются ли в ссылках target=\"_blank\" в атрибуте rel",
    },
    {
        "checklist_type": "wstg",
        "check_id": "WSTG-APIT-01",
        "category": "API Testing",
        "name": "Тестирование GraphQL",
        "short_description": "",
        "goal": "- Убедиться, что развёрнута безопасная и готовая к промышленной эксплуатации конфигурация\n- Протестировать все входные поля на защиту от классических атак.\n- Убедиться, что применяются надлежащая аутентификация и контроль доступа.",
    },
]


_MASTG_ANDROID_ITEMS = [
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0200", "category": "MASVS-STORAGE", "name": "Files Written to External Storage", "short_description": "", "goal": "Проверка обеспечения безопасности файлов приложения, хранящихся во внешних директориях"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0201", "category": "MASVS-STORAGE", "name": "Runtime Use of APIs to Access External Storage", "short_description": "", "goal": "Динамическая проверка использования API для получения доступа к файлам во внешних директориях"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0202", "category": "MASVS-STORAGE", "name": "References to APIs and Permissions for Accessing External Storage", "short_description": "", "goal": "Проверка использования методов записи файлов во внешние директории"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0203", "category": "MASVS-STORAGE", "name": "Runtime Use of Logging APIs", "short_description": "", "goal": "Проверка файлов журнала событий"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0207", "category": "MASVS-STORAGE", "name": "Runtime Storage of Unencrypted Data in the App", "short_description": "", "goal": "Проверка файлов приложения на наличие критичной информации во внутренней директории"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0216", "category": "MASVS-STORAGE", "name": "Sensitive Data Not Excluded From Backup", "short_description": "", "goal": "Исключение критичной информации из резервных копий"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0231", "category": "MASVS-STORAGE", "name": "References to Logging APIs", "short_description": "", "goal": "Проверка фиксации критичной информации в журналах событий"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0262", "category": "MASVS-STORAGE", "name": "References to Backup Configurations Not Excluding Sensitive Data", "short_description": "", "goal": "Настройки правил создания резервных копий"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0204", "category": "MASVS-CRYPTO", "name": "Insecure Random API Usage", "short_description": "", "goal": "Проверка методов генерации случайных чисел"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0205", "category": "MASVS-CRYPTO", "name": "Non-random Sources Usage", "short_description": "", "goal": "Проверка безопасного использования нерандомных случайных чисел"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0208", "category": "MASVS-CRYPTO", "name": "Insufficient Key Sizes", "short_description": "", "goal": "Проверка размера ключей шифрования"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0212", "category": "MASVS-CRYPTO", "name": "Use of Hardcoded Cryptographic Keys in Code", "short_description": "", "goal": "Проверка использования статичных ключей шифрования"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0221", "category": "MASVS-CRYPTO", "name": "Broken Symmetric Encryption Algorithms", "short_description": "", "goal": "Использование слабых алгоритмов шифрования"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0232", "category": "MASVS-CRYPTO", "name": "Broken Symmetric Encryption Modes", "short_description": "", "goal": "Использование слабых режимов шифрования"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0307", "category": "MASVS-CRYPTO", "name": "References to Asymmetric Key Pairs Used For Multiple Purposes", "short_description": "", "goal": "Использование ассиметричных ключей в различных частях приложения"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0308", "category": "MASVS-CRYPTO", "name": "Runtime Use of Asymmetric Key Pairs Used For Multiple Purposes", "short_description": "", "goal": "Динамическая проверка использования ассиметричных ключей в различных частях приложения"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0312", "category": "MASVS-CRYPTO", "name": "References to Explicit Security Provider in Cryptographic APIs", "short_description": "", "goal": "Проверка использования устаревших криптопровайдеров"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0017", "category": "MASVS-AUTH", "name": "Testing Confirm Credentials", "short_description": "", "goal": "Проверка методов подтверждения учетных записей"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0217", "category": "MASVS-NETWORK", "name": "Insecure TLS Protocols Explicitly Allowed in Code", "short_description": "", "goal": "Использование небезопасной версии TLS протокола"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0218", "category": "MASVS-NETWORK", "name": "Insecure TLS Protocols in Network Traffic", "short_description": "", "goal": "Проверка использования небезопасной версии TLS протокола во время передачи данных"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0233", "category": "MASVS-NETWORK", "name": "Hardcoded HTTP URLs", "short_description": "", "goal": "Проверка исходного кода на наличие статичных строк HTTP://"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0235", "category": "MASVS-NETWORK", "name": "Android App Configurations Allowing Cleartext Traffic", "short_description": "", "goal": "Конфигурация сетевого трафика на уровне приложения – разрешена передача данных без шифрования"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0236", "category": "MASVS-NETWORK", "name": "Cleartext Traffic Observed on the Network", "short_description": "", "goal": "Динамическая проверка передачи нешифрованных данных в сетевом трафике"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0242", "category": "MASVS-NETWORK", "name": "Missing Certificate Pinning in Network Security Configuration", "short_description": "", "goal": "Наличие проверок сертификатов в настройках сетевой конфигурации приложения"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0243", "category": "MASVS-NETWORK", "name": "Expired Certificate Pins in the Network Security Configuration", "short_description": "", "goal": "Проверка срока действия сертификатов в настройках сетевой конфигурации"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0244", "category": "MASVS-NETWORK", "name": "Missing Certificate Pinning in Network Traffic", "short_description": "", "goal": "Динамическая проверка сертификатов при передаче данных по сети"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0282", "category": "MASVS-NETWORK", "name": "Unsafe Custom Trust Evaluation", "short_description": "", "goal": "Тестирование методов проверки сертификатов"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0283", "category": "MASVS-NETWORK", "name": "Incorrect Implementation of Server Hostname Verification", "short_description": "", "goal": "Проверка поля Hostname Server при валидации сертификата"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0284", "category": "MASVS-NETWORK", "name": "Incorrect SSL Error Handling in WebViews", "short_description": "", "goal": "Проверка обработки ошибок SSL в WebViews"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0285", "category": "MASVS-NETWORK", "name": "Outdated Android Version Allowing Trust in User-Provided CAs", "short_description": "", "goal": "Проверка использования приложения на устаревших версий Андроид, где ОС по умолчанию доверяет пользовательским сертификатам"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0286", "category": "MASVS-NETWORK", "name": "Network Security Configuration Allowing Trust in User-Provided CAs", "short_description": "", "goal": "Проверка параметров Network Security Configuration на наличие доверия пользовательских сертификатов"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0295", "category": "MASVS-NETWORK", "name": "GMS Security Provider Not Updated", "short_description": "", "goal": "Проверка версии GMS Security Provider"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0007", "category": "MASVS-PLATFORM", "name": "Determining Whether Sensitive Stored Data Has Been Exposed via IPC Mechanisms", "short_description": "", "goal": "Проверка безопасного хранения и доступ к критичной информации через компоненты приложения"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0028", "category": "MASVS-PLATFORM", "name": "Testing Deep Links", "short_description": "", "goal": "Тестирование Deep Links"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0029", "category": "MASVS-PLATFORM", "name": "IPC", "short_description": "", "goal": "Проверка возможности раскрытия чувствительной информации через IPC"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0030", "category": "MASVS-PLATFORM", "name": "Testing for Vulnerable Implementation of PendingIntent", "short_description": "", "goal": "Тестирование реализации PendingIntent"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0033", "category": "MASVS-PLATFORM", "name": "Testing for Java Objects Exposed Through WebViews", "short_description": "", "goal": "Тестирование объектов Java, раскрываемых через WebViews"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0035", "category": "MASVS-PLATFORM", "name": "Testing for Overlay Attacks", "short_description": "", "goal": "Проверка Overlay Attacks"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0250", "category": "MASVS-PLATFORM", "name": "References to Content Provider Access in WebViews", "short_description": "", "goal": "Проверка настроек безопасного обращения к Content Provider через WebView"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0251", "category": "MASVS-PLATFORM", "name": "Runtime Content Provider Access in WebViews", "short_description": "", "goal": "Динамическая проверка безопасного обращения к Content Provider через WebView"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0252", "category": "MASVS-PLATFORM", "name": "References to Local File Access in WebViews", "short_description": "", "goal": "Проверка настроек доступ к локальным файлам через WebView"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0253", "category": "MASVS-PLATFORM", "name": "Runtime Use of Local File Access APIs in WebViews", "short_description": "", "goal": "Динамическая проверка настроек доступ к локальным файлам через WebView"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0258", "category": "MASVS-PLATFORM", "name": "References to Keyboard Caching Attributes in UI Elements", "short_description": "", "goal": "Проверка настроек кеширования введенных данных в UI элементах"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0289", "category": "MASVS-PLATFORM", "name": "Runtime Verification of Sensitive Content Exposure in Screenshots During App Backgrounding", "short_description": "", "goal": "Проверка маскирования критичной информации на снимках экрана, во время нахождения приложения на заднем плане"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0291", "category": "MASVS-PLATFORM", "name": "References to Screen Capturing Prevention APIs", "short_description": "", "goal": "Блокирование функций создания снимков экрана"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0315", "category": "MASVS-PLATFORM", "name": "Sensitive Data Exposed via Notifications", "short_description": "", "goal": "Раскрытие критичной информации через функции Нотификации"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0316", "category": "MASVS-PLATFORM", "name": "App Exposing User Authentication Data in Text Input Fields", "short_description": "", "goal": "Раскрытие пользовательской информации в полях ввода"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0036", "category": "MASVS-CODE", "name": "Testing Enforced Updating", "short_description": "", "goal": "Тестирование принудительного обновления"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0222", "category": "MASVS-CODE", "name": "Position Independent Code (PIC) Not Enabled", "short_description": "", "goal": "Проверить, что нативные библиотеки скомпилированы без Position Independent Code (PIC)"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0223", "category": "MASVS-CODE", "name": "Stack Canaries Not Enabled", "short_description": "", "goal": "Проверить, что нативные библиотеки скомпилированы без stack canaries"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0245", "category": "MASVS-CODE", "name": "References to Platform Version APIs", "short_description": "", "goal": "Проверить версию APIs платформы"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0272", "category": "MASVS-CODE", "name": "Identify Dependencies with Known Vulnerabilities in the Android Project", "short_description": "", "goal": "Анализ используемых библиотек на наличие известных уязвимостей"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0274", "category": "MASVS-CODE", "name": "Dependencies with Known Vulnerabilities in the App's SBOM", "short_description": "", "goal": "Анализ используемых библиотек на наличие известных уязвимостей в Software Bill of Material (SBOM)"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0049", "category": "MASVS-RESILIENCE", "name": "Testing Emulator Detection", "short_description": "", "goal": "Тестирование обнаружения эмулятора"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0050", "category": "MASVS-RESILIENCE", "name": "Testing Runtime Integrity Checks", "short_description": "", "goal": "Проверка целостности приложения во время выполнения"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0047", "category": "MASVS-RESILIENCE", "name": "Testing File Integrity Checks", "short_description": "", "goal": "Тестирование проверок целостности файлов"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0051", "category": "MASVS-RESILIENCE", "name": "Testing Obfuscation", "short_description": "", "goal": "Тестирование обфускации"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0048", "category": "MASVS-RESILIENCE", "name": "Testing Reverse Engineering Tools Detection", "short_description": "", "goal": "Тестирование обнаружения средств реверс инжиниринга"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0046", "category": "MASVS-RESILIENCE", "name": "Testing Anti-Debugging Detection", "short_description": "", "goal": "Тестирование обнаружения антиотладочных средств"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0224", "category": "MASVS-RESILIENCE", "name": "Usage of Insecure Signature Version", "short_description": "", "goal": "Проверка цифровой подписи приложения"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0225", "category": "MASVS-RESILIENCE", "name": "Usage of Insecure Signature Key Size", "short_description": "", "goal": "Проверка размера ключа электронной подписи"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0226", "category": "MASVS-RESILIENCE", "name": "Debuggable Flag Enabled in the AndroidManifest", "short_description": "", "goal": "Проверка параметра Debuggable в AndroidManifest"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0227", "category": "MASVS-RESILIENCE", "name": "Debugging Enabled for WebViews", "short_description": "", "goal": "Проверка параметра Debuggable в объектах класса WebViews"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0247", "category": "MASVS-RESILIENCE", "name": "References to APIs for Detecting Secure Screen Lock", "short_description": "", "goal": "Проверка значений методов блокировки экрана устройства"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0249", "category": "MASVS-RESILIENCE", "name": "Runtime Use of Secure Screen Lock Detection APIs", "short_description": "", "goal": "Динамическая проверка состояния функции блокировки экрана"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0263", "category": "MASVS-RESILIENCE", "name": "Logging of StrictMode Violations", "short_description": "", "goal": "Проверка журналирования событий нарушения ограниченного режима"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0264", "category": "MASVS-RESILIENCE", "name": "Runtime Use of StrictMode APIs", "short_description": "", "goal": "Динамическая проверка журналирования событий нарушения ограниченного режима"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0265", "category": "MASVS-RESILIENCE", "name": "References to StrictMode APIs", "short_description": "", "goal": "Проверка использования ограниченного режима"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0288", "category": "MASVS-RESILIENCE", "name": "Debugging Symbols in Native Binaries", "short_description": "", "goal": "Проверка отладочных символов в нативных библиотеках"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0324", "category": "MASVS-RESILIENCE", "name": "References to Root Detection Mechanisms", "short_description": "", "goal": "Проверка использования механизмов выявления root пользователя"},
    {"checklist_type": "mstg_android", "check_id": "MASTG-TEST-0325", "category": "MASVS-RESILIENCE", "name": "Runtime Use of Root Detection Techniques", "short_description": "", "goal": "Динамическая проверка механизмов выявления root пользователя"},
]


def get_checklist_items(report_type: str) -> list[dict]:
    if report_type == "web":
        return _WSTG_ITEMS
    if report_type == "android":
        return _MASTG_ANDROID_ITEMS
    return []
